// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkShopData.Models;

public partial class Category
{
    public int CategoryId { get; set; }

    public int? ProductId { get; set; }

    public string CategoryName { get; set; }

    public string Type { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}